version: "3.11.7"

x-servie-volumes: &service-volumes
  - ./:/app/:rw,cached

x-databes-variables: &database-variables
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

x-app-variables: &app-variables
  <<: *database-variables  
  POSTGRES_HOST: postgres

services:
  website:
    image: personal-website:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    depends_on:
      - db_migrate
    ports:
      - "8000:8000"

  db_migrate:
    image: personal-website:latest
    command: python manage.py migrate
    volumes: *service-volumes
    environment: *app-variables
    depends_on:
      - postgres

  
  postgres: 
    image: postgres
    ports: 
      - "5433:5432"
    environment: *database-variables
    
  